// we used moongoose
import mongoose, { Schema, model, models } from "mongoose";


export const video_dimensions={
    width : 1080,
    height:1920
} as const ;

export interface Ivideo {
 
    


  _id?: mongoose.Types.ObjectId; // id is auto matic generated by moogose and the ? symbol kabhi id generated hogi ya kabhi nhi hogi to
  createAT?: Date;
  updatedAT?: Date;
}
