// we used moongoose
import mongoose, { Schema, model, models } from "mongoose";

export const video_dimensions = {
    width: 1080,
    height: 1920,
} as const;

export interface Ivideo {
    title: string;
    description: string;
    videourl: string;
    thumbnailurl: string;
    controls?: boolean;
    transformation?: {
        height: number;
        width: number;
        quality?: number;
    };

    _id?: mongoose.Types.ObjectId; // id is auto matic generated by moogose and the ? symbol kabhi id generated hogi ya kabhi nhi hogi to
}

const videoSchema = new Schema<Ivideo>(
    {
        title: { type: String, required: true },
        thumbnailurl: { type: String, required: true },
        description: { type: String, required: true },
        videourl: { type: String, required: true },
        controls: { type: Boolean, default: true },
        transformation: {
            height: {
                type: Number,
                default: video_dimensions.height,
            },
            width: {
                type: Number,
                default: video_dimensions.width,
            },
            quality: { type: Number, min: 1, max: 100 },
        },
    },
    {
        timestamps: true,
    }
);
// if model is made then used if not then create with my designed model type
const video = models?.video || model<Ivideo>("video", videoSchema);
export default video;
